  <div class="footer-bottom">
               <div class="container">
                  <div class="row">
                     <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 "> &copy; Copyright 2016 by <a href="#">GemSparX</a>. All Rights Reserved. Powered by :<a href="http://www.indiftech.com">Indif Technologies Inc.</a></div>
                     
                  </div>
               </div>
            </div>
            <!-- Footer Bottom End --> 