         <footer id="footer">
            <!-- Footer Top Start -->
            <div class="footer-top">
               <div class="container">
                  <div class="row">
                     <section class="col-lg-3 col-md-3 col-xs-12 col-sm-3 footer-one">
                        <h3>About</h3>
                        <p>
                          GEMSPARX, Sacramento, California based company has over 25 years of experience in the Diamond Industry. GEMSPARX strives to provide it's clients the finest cut diamonds at most competitive prices.
                        </p>
                     </section>
                     <section class="col-lg-3 col-md-3 col-xs-12 col-sm-3 footer-two">
                        <h3>Mission</h3>
                       <p>
                         GEMSPARX mission is to provide exquisite designer jewelry and Diamonds to their customers with top quality manufacturing, utmost trust, exceptional customer service and unmatched value.
                         
                       </p>
                     </section>
                     <section class="col-lg-3 col-md-3 col-xs-12 col-sm-3 footer-three">
                        <h3>Contact Us</h3>
                        <ul class="contact-us">
                           <li>
                              <i class="fa fa-map-marker"></i>
                              <p> 
                                 <strong class="contact-pad">Address:</strong>1500 West El Camino Ave, Ste 452,<br>Sacramento, CA 95835<br/>USA 
                              </p>
                           </li>
                           <li>
                              <i class="fa fa-phone"></i>
                              <p><strong>Phone:</strong> 1-888-320-more(6673)
                              </p>
                           </li>
                           <li>
                              <i class="fa fa-envelope"></i>
                              <p><strong>Email:</strong><a href="mailto:info@gemsparx.com">info@gemsparx.com</a></p>
                           </li>
                        </ul>
                     </section>
                     <section class="col-lg-3 col-md-3 col-xs-12 col-sm-3 footer-four">
                        <h3>Our Selection</h3>
                        <table><tr>
                          <td><img src="/images/picicon1.jpg"><img src="/images/picicon2.jpg"><img src="/images/picicon3.jpg"></td>
                          </tr> <tr>
                          <td>
                            <img src="/images/picicon4.jpg">
                              <img src="/images/picicon5.jpg">
                                <img src="/images/picicon6.jpg">
                          </td>
                        </tr></table>
                     </section>
                  </div>
               </div>
            </div>
            <!-- Footer Top End --> 
            <!-- Footer Bottom Start -->
            <div class="footer-bottom">
               <div class="container">
                  <div class="row">
                     <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 "> &copy; Copyright 2016 by <a href="#">Gemsparx</a>. All Rights Reserved.  <br>Powered by: <a href="http://www.indiftech.com">Indif Technologies Inc.</a></div>
                     <div class="col-lg-6 col-md-6 col-xs-12 col-sm-6 ">
                        <ul class="social social-icons-footer-bottom">
                           <li class="facebook"><a href="https://www.facebook.com/gemsparx" data-toggle="tooltip" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                          <li class="facebook"> <a href="https://www.youtube.com/channel/UCMrHEQrDvqsfOSwVyAHwFEQ" data-toggle="tooltip" title="Youtube"><i class="fa fa-youtube"></i>
                            <li class="facebook"><a href="https://plus.google.com/117477665872680343513" data-toggle="tooltip" title="Google+"><i class="fa fa-google-plus"></i>
                             <li class="twitter"><a href="https://twitter.com/hashtag/gemsparx?src=hash" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                              </a>
                            </li>
                            </a>
                          </li>
                          <!-- <li class="twitter"><a href="#" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                           <li class="dribbble"><a href="#" data-toggle="tooltip" title="Dribble"><i class="fa fa-dribbble"></i></a></li>
                           <li class="linkedin"><a href="#" data-toggle="tooltip" title="LinkedIn"><i class="fa fa-linkedin"></i></a></li>
                           <li class="rss"><a href="#" data-toggle="tooltip" title="Rss"><i class="fa fa-rss"></i></a></li>-->
                         </ul>
                     </div>
                  </div>
               </div>
            </div>
            <!-- Footer Bottom End --> 
         </footer>