<!-- Header Top Bar Start -->
<div class="top-bar">
  <div class="slidedown collapse">
    <div class="container">
      <div class="phone-email pull-left">
        <a>
          <i class="fa fa-phone"></i> Call Us : 1-888-320-more(6673)
        </a>
        <a href="info@gemsparx.com">
          <i class="fa fa-envelope"></i> Email : info@gemsparx.com
        </a>
      </div>
      <div class="pull-right">


      </div>
    </div>
  </div>
</div>
<!-- Header Top Bar End -->