
                  <!-- Mobile Menu Start -->
                  <div class="mobile navbar-header">
                     <a class="navbar-toggle" data-toggle="collapse" href=".navbar-collapse">
                     <i class="fa fa-bars fa-2x"></i>
                     </a> 
                  </div>
                  <!-- Mobile Menu End -->
                  <!-- Menu Start -->
                  <nav class="collapse navbar-collapse menu">
                     <ul class="nav navbar-nav sf-menu">
                       
                       <li>
                         <a href="LogOut.aspx">
                           Log Out
                           <span class="sf-sub-indicator">

                           </span>
                         </a>

                       </li>
                       
                     </ul>
                  </nav>
                  <!-- Menu End --> 