<!-- Logo Start -->
<div class="logo pull-left">
  <h1>
    <a href="/">
      <img src="/img/logo.png" alt="GemSparX" >
                        </a>
  </h1>
</div>
<!-- Logo End -->
                  <!-- Mobile Menu Start -->
                  <div class="mobile navbar-header">
                     <a class="navbar-toggle" data-toggle="collapse" href=".navbar-collapse">
                     <i class="fa fa-bars fa-2x"></i>
                     </a> 
                  </div>
                  <!-- Mobile Menu End -->
                  <!-- Menu Start -->
                  <nav class="collapse navbar-collapse menu">
                     <ul class="nav navbar-nav sf-menu">
                        <li>
                           <a id="current" href="/">
                           Home
                           <span class="sf-sub-indicator">
                           <i class="fa fa-angle-down "></i>
                           </span>
                           </a>
                           <ul> <li>
                         <a href="#">
                           About us
                           <span class="sf-sub-indicator">
                             <i class="fa fa-angle-down"></i>
                           </span>
                         </a>
                         <ul>
                           <li>
                             <a href="about.aspx" class="sf-with-ul">Our Company</a>
                           </li>
                           <li>
                             <a href="contact.aspx" class="sf-with-ul">Contact Us</a>
                           </li>
                          <li>
                             <a href="testimonials.aspx" class="sf-with-ul">Testimonials</a>
                           </li>
                         </ul>
                       </li>
                         <li>
                         <a href="#">
                           Education
                           <span class="sf-sub-indicator">
                             <i class="fa fa-angle-down"></i>
                           </span>
                         </a>
                         <ul>
                           <li>
                             <a href="Shapes.aspx" class="sf-with-ul">Diamond Shapes</a>
                           </li>
                           <li>
                             <a href="learn4cs.aspx" class="sf-with-ul">4 C's</a>
                           </li>
                           <li>
                             <a href="hca.aspx" class="sf-with-ul">Holloway Cut Adviser</a>
                           </li>
                         </ul>
                       </li>
                       </ul>
                        </li>
					<li><a href="https://shop.gemsparx.com/">Jewelry Designs
					<span class="sf-sub-indicator">
                              <i class="fa fa-angle-down"></i>
                            </span>
							</a>
							<ul>
                              <li><a href="https://shop.gemsparx.com/collections/kayte-christensen">
 KAYTE Christensen Collection<span class="sf-sub-indicator">
                             <i class="fa fa-angle-down"></i>
                           </span></a>
						   <ul>
								<li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/engagement-rings" class="sf-with-ul">Engagement Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/wedding-rings" class="sf-with-ul">Wedding Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/pendants" class="sf-with-ul">Pendants</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/earrings" class="sf-with-ul">Fashion Earrings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/mens-rings" class="sf-with-ul">Men's Rings</a>
							   </li>
<li>
								 <a href="https://shop.gemsparx.com/collections/kayte-christensen/bracelets" class="sf-with-ul">Bracelets</a>
							   </li>
							</ul>
						   </li>
                              
                              <li>
                                <a href="https://shop.gemsparx.com/collections/gemsparx">
GEMSPARX Signature Collection<span class="sf-sub-indicator">
                             <i class="fa fa-angle-down"></i>
                           </span></a>
						   <ul>
								<li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/engagement-rings" class="sf-with-ul">Engagement Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/wedding-rings" class="sf-with-ul">Wedding Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/pendants" class="sf-with-ul">Pendants</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/earrings" class="sf-with-ul">Fashion Earrings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/mens-rings" class="sf-with-ul">Men's Rings</a>
							   </li>
<li>
								 <a href="https://shop.gemsparx.com/collections/gemsparx/bracelets" class="sf-with-ul">Bracelets</a>
							   </li>
							</ul>
                              </li>
							  <li>
                                <a href="https://shop.gemsparx.com/collections/naima-mora">NAIMA Mora<br />Collection<span class="sf-sub-indicator">
                             <i class="fa fa-angle-down"></i>
                           </span></a>
						   <ul>
								<li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/engagement-rings" class="sf-with-ul">Engagement Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/wedding-rings" class="sf-with-ul">Wedding Rings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/pendants" class="sf-with-ul">Pendants</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/earrings" class="sf-with-ul">Fashion Earrings</a>
							   </li>
							   <li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/mens-rings" class="sf-with-ul">Men's Rings</a>
							   </li>
<li>
								 <a href="https://shop.gemsparx.com/collections/naima-mora/bracelets" class="sf-with-ul">Bracelets</a>
							   </li>

							</ul>
                              </li>
							  
                            </ul>
		   
		   </li>
                  
	
  		      <li><a href="SearchMain.aspx">
                            Diamond Search
                            <span class="sf-sub-indicator">
                              <i class="fa fa-angle-down"></i>
                            </span>
                            </a>
                            <ul>
                              <!--<li><a href="SearchMain.aspx" class="sf-with-ul">Basic</a></li>-->
				<li><a href="<%= Page.ResolveUrl("~/SearchMain.aspx") %>">Basic</a></li>
                              
                              <li>
                                <!--<a href="SearchColored.aspx" class="sf-with-ul">Colored</a>-->
				 <li><a href="<%= Page.ResolveUrl("~/SearchColored.aspx") %>">Colored</a></li>
                              </li>
                            </ul>
                         </li>

                      
  

<li>
                         <a href="faq.aspx">
                           FAQs
                           <span class="sf-sub-indicator">
                            
                           </span>
                         </a>

                       </li>
                       


                      


                       <li>
                         <a href="rewards.aspx">
                           Rewards Program
                           <span class="sf-sub-indicator">
                            
                           </span>
                         </a>

                       </li>
                     

                       <li>                      
                           <a href="~/Admin/AdminLogin.aspx" runat="server"  id="txtAdminLogin">
                             Admin
                             <span class="sf-sub-indicator">
                           </span>
                         </a>
                       </li>

                       <li>
                         <a href="LogOut.aspx" runat="server"  id="txtLogout" visible="false">
                           Log Out
                           <span class="sf-sub-indicator">

                           </span>
                         </a>

                       </li>
                       
                     </ul>
                  </nav>
                  <!-- Menu End --> 