   <link rel="stylesheet" href="/css/bootstrap.css">
      <link rel="stylesheet" href="/css/bootstrap-theme.css">
      <link rel="stylesheet" href="/css/fonts/font-awesome//css/font-awesome.css">
      <link rel="stylesheet" href="/css/animations.css" media="screen">
      <link rel="stylesheet" href="/css/superfish.css" media="screen">
      <link rel="stylesheet" href="/css/revolution-slider//css/settings.css" media="screen">
      <link rel="stylesheet" href="/css/prettyPhoto.css" media="screen">
      <!-- Theme CSS -->
      <link rel="stylesheet" href="/css/style.css">
      <!-- Skin -->
      <link rel="stylesheet" href="/css/colors/blue.css" class="colors">
      <!-- Responsive CSS -->
      <link rel="stylesheet" href="/css/theme-responsive.css">
      <!-- Switcher CSS -->
      <link href="/css/switcher.css" rel="stylesheet">
      <link href="/css/spectrum.css" rel="stylesheet">
      <!-- Switcher CSS -->
      <link href="/css/switcher.css" rel="stylesheet">
      <link href="/css/spectrum.css" rel="stylesheet">


 <!-- Favicons -->
      <link rel="shortcut icon" href="/img/ico/favicon.ico">
      <link rel="apple-touch-icon" href="/img/ico/apple-touch-icon.png">
      <link rel="apple-touch-icon" sizes="72x72" href="/img/ico/apple-touch-icon-72.png">
      <link rel="apple-touch-icon" sizes="114x114" href="/img/ico/apple-touch-icon-114.png">
      <link rel="apple-touch-icon" sizes="144x144" href="/img/ico/apple-touch-icon-144.png">